site_name:        ODE.jl
repo_url:         https://github.com/JuliaODE/ODE.jl
site_description: Julia package for solving differential equations

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Manual:
  - Basics: man/basics.md
  - Base: man/base.md
  # - Integrators:
  # - Solvers:
  # - Options:
- Tutorials:
  - Fixed step integrator: tutorials/euler_integrator.md
  # - Adaptive step integrator:
